name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@34cfbaee7f672c76950673338facd8a73f637506 # v1.1.3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@04b0c2b8d1b97922f67eca497d7cf0bf17b8ffe1 # v1.0.5
    
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Restore Packages - client
      run: nuget restore client\Samples.sln

    - name: Build Solution - client
      run: |
        msbuild.exe client\Samples.sln /p:configuration="Release"

    - name: Restore Packages - kafka
      run: nuget restore kafka\KafkaSampleData.sln

    - name: Build Solution - kafka
      run: |
        msbuild.exe kafka\KafkaSampleData.sln /p:configuration="Release"
