name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Restore Packages - client
      run: nuget restore client\Samples.sln

    - name: Build Solution - client
      run: |
        msbuild.exe client\Samples.sln /p:configuration="Release"

    - name: Restore Packages - kafka
      run: nuget restore kafka\KafkaSampleData.sln

    - name: Build Solution - kafka
      run: |
        msbuild.exe kafka\KafkaSampleData.sln /p:configuration="Release"
